const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const rocketsData = [
  // ==================== 中国：长征系列 (CASC) ====================
  {
    name: "CZ-1",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院 (CALT)",
    status: "退役",
    firstFlight: "1970-04-24",
    history: "2次发射，2次成功 (100%)",
    height: 29.86,
    diameter: 2.25,
    mass: 81.6,
    stages: "3",
    boosters: "无",
    leoCapacity: 0.3,
    firstStageFuel: "硝酸-27S / 偏二甲肼 (UDMH)",
    firstStageEngine: "1 x YF-2A (4台YF-1A并联)",
    firstStageThrust: "1020 kN",
    secondStageFuel: "硝酸-27S / 偏二甲肼 (UDMH)",
    secondStageEngine: "1 x YF-3",
    thirdStageFuel: "固体",
    thirdStageEngine: "1 x FG-02",
    description: "中国航天的奠基之作。基于东风-4号中远程弹道导弹改进而来。1970年4月24日，它成功将中国第一颗人造地球卫星“东方红一号”送入太空，使中国成为世界上第五个独立研制并发射卫星的国家。",
    isReusable: false
  },
  {
    name: "CZ-2C",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院 (CALT)",
    status: "现役",
    firstFlight: "1982-09-09",
    history: "超过70次发射",
    height: 42.0,
    diameter: 3.35,
    mass: 233.0,
    stages: "2",
    boosters: "无",
    leoCapacity: 3.85,
    firstStageFuel: "N2O4 / UDMH",
    firstStageEngine: "4 x YF-21C",
    firstStageThrust: "2961 kN",
    secondStageFuel: "N2O4 / UDMH",
    secondStageEngine: "1 x YF-24E",
    description: "中国航天的“金牌火箭”。主要用于执行低轨遥感、科学实验卫星发射。近期加装了栅格舵以进行落区控制验证。",
    isReusable: false
  },
  {
    name: "CZ-2D",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天八院 (SAST)",
    status: "现役",
    firstFlight: "1992-08-09",
    history: "80+次发射",
    height: 41.0,
    diameter: 3.35,
    mass: 232.0,
    stages: "2",
    boosters: "无",
    leoCapacity: 3.5,
    firstStageFuel: "N2O4 / UDMH",
    firstStageEngine: "4 x YF-21C",
    firstStageThrust: "2961 kN",
    secondStageFuel: "N2O4 / UDMH",
    secondStageEngine: "1 x YF-24C",
    description: "上海航天研制的常温液体火箭。以高可靠性和快速响应著称，是太阳同步轨道任务的主力。",
    isReusable: false
  },
  {
    name: "CZ-2F",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院 (CALT)",
    status: "现役",
    firstFlight: "1999-11-20",
    history: "100% 成功率 (载人任务)",
    height: 58.34,
    diameter: 3.35,
    mass: 497.0,
    stages: "2",
    boosters: "4 x 2.25m 液体",
    leoCapacity: 8.6,
    firstStageFuel: "N2O4 / UDMH",
    firstStageEngine: "4 x YF-20B (芯级) + 4 x YF-20B (助推)",
    firstStageThrust: "5923 kN",
    secondStageFuel: "N2O4 / UDMH",
    secondStageEngine: "1 x YF-24B",
    description: "“神箭”，中国载人航天工程的专属座驾。配备逃逸塔和故障检测系统，负责神舟飞船的发射。",
    isReusable: false
  },
  {
    name: "CZ-3A",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院 (CALT)",
    status: "现役",
    firstFlight: "1994-02-08",
    height: 52.52,
    diameter: 3.35,
    mass: 241.0,
    stages: "3",
    boosters: "无",
    leoCapacity: 8.5,
    gtoCapacity: 2.6,
    firstStageFuel: "N2O4 / UDMH",
    firstStageEngine: "4 x YF-21C",
    thirdStageFuel: "液氢 / 液氧",
    thirdStageEngine: "2 x YF-75",
    description: "基于CZ-3改进，采用了更强大的氢氧第三级。它是CZ-3A、3B、3C系列的基础型号。",
    isReusable: false
  },
  {
    name: "CZ-3B",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院 (CALT)",
    status: "现役",
    firstFlight: "1996-02-15",
    height: 56.3,
    diameter: 3.35,
    mass: 459.0,
    stages: "3",
    boosters: "4 x 2.25m 液体",
    leoCapacity: 11.5,
    gtoCapacity: 5.5,
    firstStageFuel: "N2O4 / UDMH",
    firstStageEngine: "4 x YF-20C (芯级) + 4 x YF-25 (助推)",
    firstStageThrust: "5923 kN",
    thirdStageFuel: "液氢 / 液氧",
    thirdStageEngine: "2 x YF-75",
    description: "中国高轨道发射的主力。承担了北斗导航、嫦娥工程等重大任务。",
    isReusable: false
  },
  {
    name: "CZ-3C",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院 (CALT)",
    status: "现役",
    firstFlight: "2008-04-25",
    height: 54.8,
    diameter: 3.35,
    mass: 345.0,
    stages: "3",
    boosters: "2 x 2.25m 液体",
    gtoCapacity: 3.8,
    firstStageFuel: "N2O4 / UDMH",
    firstStageEngine: "4 x YF-20B",
    thirdStageFuel: "液氢 / 液氧",
    thirdStageEngine: "2 x YF-75",
    description: "介于3A和3B之间的型号，拥有2个助推器，主要用于发射天链、北斗等卫星。",
    isReusable: false
  },
  {
    name: "CZ-4B",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天八院 (SAST)",
    status: "现役",
    firstFlight: "1999-05-10",
    height: 48.0,
    diameter: 3.35,
    mass: 250.0,
    stages: "3",
    leoCapacity: 4.2,
    firstStageFuel: "N2O4 / UDMH",
    firstStageEngine: "4 x YF-21C",
    thirdStageFuel: "N2O4 / UDMH",
    thirdStageEngine: "2 x YF-40",
    description: "全常温三级液体火箭，主要执行SSO轨道发射任务。",
    isReusable: false
  },
  {
    name: "CZ-4C",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天八院 (SAST)",
    status: "现役",
    firstFlight: "2006-04-27",
    height: 48.0,
    diameter: 3.35,
    mass: 250.0,
    stages: "3",
    leoCapacity: 4.2,
    gtoCapacity: 1.5,
    firstStageFuel: "N2O4 / UDMH",
    thirdStageEngine: "2 x YF-40 (具备二次启动能力)",
    description: "CZ-4B的改进型，三级发动机具备二次启动能力，支持更复杂的轨道部署。",
    isReusable: false
  },
  {
    name: "CZ-5",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院 (CALT)",
    status: "现役",
    firstFlight: "2016-11-03",
    height: 56.97,
    diameter: 5.0,
    mass: 869.0,
    stages: "2.5",
    boosters: "4 x 3.35m 液体",
    leoCapacity: 32.0,
    gtoCapacity: 14.0,
    marsCapacity: 6.0,
    firstStageFuel: "液氢 / 液氧",
    firstStageEngine: "2 x YF-77",
    firstStageThrust: "10570 kN (含助推)",
    secondStageFuel: "液氢 / 液氧",
    secondStageEngine: "2 x YF-75D",
    description: "“胖五”，中国现役最强火箭。负责天问、嫦娥、空间站等重型任务。",
    isReusable: false
  },
  {
    name: "CZ-5B",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院 (CALT)",
    status: "现役",
    firstFlight: "2020-05-05",
    height: 53.7,
    diameter: 5.0,
    mass: 837.0,
    stages: "1.5",
    boosters: "4 x 3.35m 液体",
    leoCapacity: 25.0,
    firstStageFuel: "液氢 / 液氧",
    firstStageEngine: "2 x YF-77",
    description: "CZ-5的近地轨道版，取消第二级。专为发射空间站大型舱段设计。",
    isReusable: false
  },
  {
    name: "CZ-6",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天八院 (SAST)",
    status: "现役",
    firstFlight: "2015-09-20",
    height: 29.0,
    diameter: 3.35,
    mass: 103.0,
    stages: "3",
    leoCapacity: 1.5,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "1 x YF-100",
    secondStageEngine: "1 x YF-115",
    description: "新一代小型液体火箭。曾创下一箭20星发射纪录。",
    isReusable: false
  },
  {
    name: "CZ-6A",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天八院 (SAST)",
    status: "现役",
    firstFlight: "2022-03-29",
    height: 50.0,
    diameter: 3.35,
    mass: 530.0,
    stages: "2",
    boosters: "4 x 固体助推器",
    leoCapacity: 4.5,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "2 x YF-100",
    firstStageThrust: "7230 kN",
    description: "中国首款固液混合运载火箭。适用于高频商业组网任务。",
    isReusable: false
  },
  {
    name: "CZ-6C",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天八院 (SAST)",
    status: "现役",
    firstFlight: "2024-05-07",
    height: 43.0,
    diameter: 3.35,
    mass: 217.0,
    stages: "2",
    leoCapacity: 4.5,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "2 x YF-100",
    secondStageEngine: "1 x YF-115",
    description: "CZ-6A的精简版，去掉了固体助推器，是2吨级SSO运力的主力。",
    isReusable: false
  },
  {
    name: "CZ-7",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院 (CALT)",
    status: "现役",
    firstFlight: "2016-06-25",
    height: 53.1,
    diameter: 3.35,
    mass: 597.0,
    stages: "2.5",
    boosters: "4 x 2.25m 液体",
    leoCapacity: 13.5,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "2 x YF-100",
    secondStageEngine: "4 x YF-115",
    description: "货运飞船专属载具。在文昌执行天舟货运任务。",
    isReusable: false
  },
  {
    name: "CZ-7A",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院 (CALT)",
    status: "现役",
    firstFlight: "2020-03-16",
    height: 60.13,
    diameter: 3.35,
    mass: 573.0,
    stages: "3",
    boosters: "4 x 2.25m 液体",
    gtoCapacity: 7.0,
    firstStageFuel: "液氧 / 煤油",
    thirdStageFuel: "液氢 / 液氧",
    description: "高轨改进型，结合了CZ-7的芯一级和CZ-3A的氢氧三级，是主力高轨火箭。",
    isReusable: false
  },
  {
    name: "CZ-8",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院 (CALT)",
    status: "现役",
    firstFlight: "2020-12-22",
    height: 50.3,
    diameter: 3.35,
    mass: 356.0,
    stages: "2",
    boosters: "2 x 2.25m 液体",
    leoCapacity: 8.1,
    gtoCapacity: 4.5,
    firstStageFuel: "液氧 / 煤油",
    description: "面向商业市场开发。CZ-8R改型将实现集束回收。",
    isReusable: true
  },
  {
    name: "CZ-9",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院 (CALT)",
    status: "研发中",
    firstFlight: "预计2033",
    height: 114.0,
    diameter: 10.6,
    mass: 4350.0,
    stages: "2",
    leoCapacity: 150.0,
    marsCapacity: 44.0,
    firstStageFuel: "液氧 / 甲烷",
    firstStageEngine: "30 x YF-215",
    isReusable: true,
    recoveryMethod: "垂直回收",
    description: "中国重型运载火箭。目标支撑载人登火和深空探测。",
    isReusable: true
  },
  {
    name: "CZ-10",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院 (CALT)",
    status: "研发中",
    firstFlight: "预计2027",
    height: 92.5,
    diameter: 5.0,
    mass: 2189.0,
    stages: "3",
    boosters: "2 x 5.0m 芯级",
    leoCapacity: 70.0,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "21 x YF-100K",
    description: "新一代载人火箭。专为登月设计，A型具备回收能力。",
    isReusable: false
  },
  {
    name: "CZ-11",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院 (CALT)",
    status: "现役",
    firstFlight: "2015-09-25",
    height: 20.8,
    diameter: 2.0,
    mass: 58.0,
    stages: "4",
    leoCapacity: 0.7,
    firstStageFuel: "固体",
    description: "小型固体火箭。支持海上发射和快速响应。",
    isReusable: false
  },
  {
    name: "CZ-12",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天八院 (SAST)",
    status: "现役",
    firstFlight: "2024-11-30",
    height: 62.0,
    diameter: 3.8,
    mass: 433.0,
    stages: "2",
    leoCapacity: 12.0,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "4 x YF-100K",
    description: "3.8米直径，是中国首款可在普通铁路运输的宽箭体火箭。",
    isReusable: false
  },

  // ==================== 中国：商业航天 ====================
  {
    name: "快舟1A",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "航天科工 (ExPace)",
    status: "现役",
    height: 20.0,
    diameter: 1.4,
    mass: 30.0,
    stages: "3固体+1液体",
    leoCapacity: 0.3,
    firstStageFuel: "固体",
    description: "快速响应固体火箭，支持车载移动发射。",
    isReusable: false
  },
  {
    name: "朱雀二号",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "蓝箭航天 (LandSpace)",
    status: "现役",
    firstFlight: "2022-12-14",
    height: 49.5,
    diameter: 3.35,
    mass: 219.0,
    stages: "2",
    leoCapacity: 6.0,
    firstStageFuel: "液氧 / 甲烷",
    firstStageEngine: "4 x TQ-12",
    description: "全球首款入轨成功的液氧甲烷火箭。",
    isReusable: false
  },
  {
    name: "朱雀三号",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "蓝箭航天 (LandSpace)",
    status: "研发中",
    firstFlight: "预计2025",
    height: 76.6,
    diameter: 4.5,
    leoCapacity: 21.3,
    firstStageFuel: "液氧 / 甲烷",
    firstStageEngine: "9 x TQ-12B",
    isReusable: true,
    recoveryMethod: "垂直回收",
    description: "不锈钢材质复用火箭，目标复用20次。",
    isReusable: true
  },
  {
    name: "力箭一号",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "中科宇航 (CAS Space)",
    status: "现役",
    firstFlight: "2022-07-27",
    height: 30.0,
    diameter: 2.65,
    mass: 135.0,
    stages: "4",
    leoCapacity: 2.0,
    firstStageFuel: "固体",
    firstStageThrust: "2000 kN",
    description: "中科院背景的商业固体火箭。运力强劲。",
    isReusable: false
  },
  {
    name: "引力一号",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "东方空间 (Orienspace)",
    status: "现役",
    firstFlight: "2024-01-11",
    height: 30.0,
    diameter: 2.65,
    mass: 405.0,
    stages: "3级+4助推",
    boosters: "4 x 固体助推器",
    leoCapacity: 6.5,
    firstStageFuel: "固体",
    description: "全球起飞推力最大的固体火箭。海上发射模式。",
    isReusable: false
  },
  {
    name: "谷神星一号",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "星河动力 (Galactic Energy)",
    status: "现役",
    firstFlight: "2020-11-07",
    height: 19.0,
    diameter: 1.4,
    mass: 33.0,
    stages: "4",
    leoCapacity: 0.4,
    firstStageFuel: "固体",
    description: "中国民营航天中发射频率最高的固体火箭。",
    isReusable: false
  },
  {
    name: "天龙二号",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "天兵科技 (Space Pioneer)",
    status: "现役",
    firstFlight: "2023-04-02",
    height: 32.8,
    diameter: 3.35,
    leoCapacity: 2.0,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "3 x YF-102",
    description: "全球首款首飞即成功的民营液体火箭。",
    isReusable: false
  },
  {
    name: "天龙三号",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "天兵科技 (Space Pioneer)",
    status: "研发中",
    firstFlight: "预计2025",
    height: 71.0,
    diameter: 3.8,
    mass: 590.0,
    leoCapacity: 17.0,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "9 x TH-12",
    isReusable: true,
    recoveryMethod: "垂直回收",
    description: "对标Falcon 9的中大型复用液体火箭。",
    isReusable: true
  },
  {
    name: "双曲线一号",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "星际荣耀 (i-Space)",
    status: "现役",
    firstFlight: "2019-07-25",
    height: 20.8,
    diameter: 1.4,
    mass: 31.0,
    leoCapacity: 0.3,
    firstStageFuel: "固体",
    description: "中国首个入轨成功的民营火箭型号。",
    isReusable: false
  },
  {
    name: "智神星一号",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "星河动力 (Galactic Energy)",
    status: "研发中",
    firstFlight: "预计2025",
    height: 49.6,
    diameter: 3.35,
    mass: 220.0,
    leoCapacity: 5.0,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "7 x CQ-50",
    isReusable: true,
    recoveryMethod: "垂直回收",
    description: "“苍穹”引擎驱动的复用液体火箭。",
    isReusable: true
  },

  // ==================== 美国 & 国际 ====================
  {
    name: "Falcon 9",
    series: "SpaceX",
    country: "美国",
    manufacturer: "SpaceX",
    status: "现役",
    firstFlight: "2010-06-04",
    height: 70.0,
    diameter: 3.7,
    mass: 549.0,
    leoCapacity: 22.8,
    gtoCapacity: 8.3,
    firstStageFuel: "液氧 / 煤油 (RP-1)",
    firstStageEngine: "9 x Merlin 1D++",
    isReusable: true,
    recoveryMethod: "垂直降落 (陆地/海上)",
    description: "全球最成熟的轨道级可回收火箭。",
    isReusable: true
  },
  {
    name: "Falcon Heavy",
    series: "SpaceX",
    country: "美国",
    manufacturer: "SpaceX",
    status: "现役",
    firstFlight: "2018-02-06",
    height: 70.0,
    diameter: 3.7,
    mass: 1420.0,
    leoCapacity: 63.8,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "27 x Merlin 1D",
    isReusable: true,
    recoveryMethod: "三个一级均可垂直回收",
    description: "三枚Falcon 9一级并联，运力惊人。",
    isReusable: true
  },
  {
    name: "Starship",
    series: "SpaceX",
    country: "美国",
    manufacturer: "SpaceX",
    status: "测试中",
    firstFlight: "2023-04-20",
    height: 121.0,
    diameter: 9.0,
    mass: 5000.0,
    leoCapacity: 150.0,
    firstStageFuel: "液氧 / 甲烷",
    firstStageEngine: "33 x Raptor",
    isReusable: true,
    recoveryMethod: "塔架“筷子”抓取",
    description: "完全复用的星际运输系统。旨在殖民火星。",
    isReusable: true
  },
  {
    name: "SLS Block 1",
    series: "NASA",
    country: "美国",
    manufacturer: "NASA / Boeing",
    status: "现役",
    firstFlight: "2022-11-16",
    height: 98.0,
    diameter: 8.4,
    mass: 2608.0,
    leoCapacity: 95.0,
    firstStageFuel: "液氢 / 液氧",
    firstStageEngine: "4 x RS-25D",
    description: "Artemis计划载人登月的核心。",
    isReusable: false
  },
  {
    name: "Saturn V",
    series: "NASA Legacy",
    country: "美国",
    manufacturer: "Boeing/NA/Douglas",
    status: "退役",
    firstFlight: "1967-11-09",
    height: 111.0,
    diameter: 10.0,
    mass: 2822.0,
    leoCapacity: 140.0,
    firstStageFuel: "液氧 / RP-1",
    firstStageEngine: "5 x F-1",
    description: "阿波罗登月计划的功勋火箭。人类推力最大的飞船载具。",
    isReusable: false
  },
  {
    name: "STS（航天飞机）",
    series: "NASA Legacy",
    country: "美国",
    manufacturer: "Rockwell/Thiokol",
    status: "退役",
    firstFlight: "1981-04-12",
    height: 56.0,
    diameter: 8.7,
    mass: 2030.0,
    leoCapacity: 24.4,
    firstStageFuel: "固体+液氢/液氧",
    firstStageEngine: "3 x RS-25",
    description: "轨道飞行器+外储箱+双助推器。定义了一个航天时代。",
    isReusable: true
  },
  {
    name: "Delta IV Heavy",
    series: "ULA Legacy",
    country: "美国",
    manufacturer: "ULA",
    status: "退役",
    firstFlight: "2004-12-21",
    height: 70.7,
    diameter: 5.1,
    mass: 733.0,
    leoCapacity: 28.8,
    firstStageFuel: "液氢 / 液氧",
    firstStageEngine: "3 x RS-68A",
    description: "曾经的世界最强氢氧火箭。主要发射重型机密载荷。",
    isReusable: false
  },
  {
    name: "Atlas V",
    series: "ULA",
    country: "美国",
    manufacturer: "ULA",
    status: "现役/退役中",
    firstFlight: "2002-08-21",
    height: 58.3,
    diameter: 3.8,
    mass: 590.0,
    leoCapacity: 18.8,
    firstStageFuel: "液氧 / RP-1",
    firstStageEngine: "1 x RD-180",
    description: "极高可靠性。采用俄制RD-180引擎。",
    isReusable: false
  },
  {
    name: "Vulcan Centaur",
    series: "ULA",
    country: "美国",
    manufacturer: "ULA",
    status: "现役",
    firstFlight: "2024-01-08",
    height: 61.6,
    diameter: 5.4,
    mass: 546.0,
    leoCapacity: 27.2,
    firstStageFuel: "液氧 / 甲烷",
    firstStageEngine: "2 x BE-4",
    description: "ULA的新一代主力，旨在替代Atlas和Delta。",
    isReusable: true
  },
  {
    name: "New Glenn",
    series: "Blue Origin",
    country: "美国",
    manufacturer: "Blue Origin",
    status: "即将首飞",
    firstFlight: "预计2025",
    height: 98.0,
    diameter: 7.0,
    leoCapacity: 45.0,
    firstStageFuel: "液氧 / 甲烷",
    firstStageEngine: "7 x BE-4",
    isReusable: true,
    recoveryMethod: "垂直降落",
    description: "贝佐斯的巨型复用火箭。拥有巨大的7米整流罩。",
    isReusable: true
  },
  {
    name: "Ariane 6",
    series: "Ariane",
    country: "欧洲",
    manufacturer: "Arianespace",
    status: "现役",
    firstFlight: "2024-07-09",
    height: 63.0,
    diameter: 5.4,
    mass: 860.0,
    leoCapacity: 21.6,
    firstStageFuel: "液氢 / 液氧",
    firstStageEngine: "1 x Vulcain 2.1",
    description: "维持欧洲航天自主权的关键。采用模块化助推设计。",
    isReusable: false
  },
  {
    name: "H3",
    series: "H-II",
    country: "日本",
    manufacturer: "JAXA",
    status: "现役",
    firstFlight: "2023-03-07",
    height: 63.0,
    diameter: 5.2,
    mass: 574.0,
    leoCapacity: 16.5,
    firstStageFuel: "液氢 / 液氧",
    firstStageEngine: "LE-9",
    description: "日本新旗舰。首款采用膨胀排放循环一级引擎的火箭。",
    isReusable: false
  },
  {
    name: "Angara A5",
    series: "Angara",
    country: "俄罗斯",
    manufacturer: "Khrunichev",
    status: "现役",
    firstFlight: "2014-12-23",
    height: 55.4,
    diameter: 8.9,
    mass: 775.0,
    leoCapacity: 26.0,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "RD-191",
    description: "俄罗斯自研的新一代重型火箭。取代质子号。",
    isReusable: false
  }
];

async function seed() {
  console.log('Starting Global Rocket Database enriched seeding...');
  
  // 清空现有火箭数据，确保与 seed 数据严格同步
  await prisma.rocket.deleteMany({});
  console.log('Existing rocket data cleared.');
  
  for (const r of rocketsData) {
    try {
      await prisma.rocket.upsert({
        where: { name: r.name },
        update: r,
        create: r
      });
      console.log(`Enriched Spec: ${r.name}`);
    } catch (e) {
      console.error(`Error processing ${r.name}: ${e.message}`);
    }
  }
  
  console.log('Database enriched and synchronized successfully.');
}

seed()
  .catch(e => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });