const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const rocketsData = [
  // ==================== 中国：长征系列 (CASC) ====================
  {
    name: "CZ-1",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院",
    status: "退役",
    firstFlight: "1970-04-24",
    history: "2次发射，2次成功 (100%)",
    height: 29.86,
    diameter: 2.25,
    mass: 81.6,
    stages: "3",
    boosters: "无",
    leoCapacity: 0.3,
    firstStageFuel: "硝酸-27S / 偏二甲肼 (UDMH)",
    firstStageEngine: "1 x YF-2A (由4台YF-1A并联)",
    firstStageThrust: "1020 kN",
    secondStageFuel: "硝酸-27S / 偏二甲肼 (UDMH)",
    secondStageEngine: "1 x YF-3",
    thirdStageFuel: "固体",
    thirdStageEngine: "1 x FG-02",
    description: "中国航天的奠基之作。基于东风-4号中远程弹道导弹改进而来，第三级采用了当时刚刚研制成功的固体发动机。1970年4月24日，它成功将中国第一颗人造地球卫星“东方红一号”送入太空，使中国成为继苏、美、法、日之后第五个独立研制并发射人造地球卫星的国家。",
    isReusable: false
  },
  {
    name: "CZ-2C",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院",
    status: "现役",
    firstFlight: "1982-09-09",
    history: "超过70次发射，极高成功率",
    height: 42.0,
    diameter: 3.35,
    mass: 233.0,
    stages: "2",
    boosters: "无",
    leoCapacity: 3.85,
    firstStageFuel: "四氧化二氮 (N2O4) / 偏二甲肼 (UDMH)",
    firstStageEngine: "4 x YF-21C",
    firstStageThrust: "2961 kN",
    secondStageFuel: "N2O4 / UDMH",
    secondStageEngine: "1 x YF-24E (1台主机 + 4台游机)",
    description: "中国航天的“金牌火箭”。作为长征二号家族的基础型号，它经久不衰，主要用于执行低轨遥感卫星、科学实验卫星的发射任务。近年来通过加装离轨帆和栅格舵，正在进行子级落区控制技术的验证。",
    isReusable: false
  },
  {
    name: "CZ-2D",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天八院",
    status: "现役",
    firstFlight: "1992-08-09",
    history: "80+次发射",
    height: 41.0,
    diameter: 3.35,
    mass: 232.0,
    stages: "2",
    boosters: "无",
    leoCapacity: 3.5,
    gtoCapacity: null,
    firstStageFuel: "N2O4 / UDMH",
    firstStageEngine: "4 x YF-21C",
    firstStageThrust: "2961 kN",
    secondStageFuel: "N2O4 / UDMH",
    secondStageEngine: "1 x YF-24C",
    description: "由上海航天技术研究院（SAST）研制的常温液体火箭。虽然名为“2D”，但它其实是基于风暴一号火箭技术发展而来的。主要用于太阳同步轨道（SSO）任务，以其极高的可靠性和快速响应能力，成为商业航天拼车发射的热门选择。",
    isReusable: false
  },
  {
    name: "CZ-2F",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院",
    status: "现役",
    firstFlight: "1999-11-20",
    history: "100% 成功率 (载人/天宫任务)",
    height: 58.34,
    diameter: 3.35,
    mass: 497.0,
    stages: "2",
    boosters: "4 x 2.25m 液体 (N2O4/UDMH)",
    leoCapacity: 8.6,
    firstStageFuel: "N2O4 / UDMH",
    firstStageEngine: "4 x YF-20B (芯级) + 4 x YF-20B (助推)",
    firstStageThrust: "5923 kN (全推力)",
    secondStageFuel: "N2O4 / UDMH",
    secondStageEngine: "1 x YF-24B",
    description: "“神箭”，中国载人航天工程的专属座驾。基于长征二号E改进，增加了故障检测处理系统和逃逸系统，可靠性指标提升至0.97。它成功发射了从神舟一号到神舟十九号的所有飞船，以及天宫一号、二号目标飞行器。",
    isReusable: false
  },
  {
    name: "CZ-3B",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院",
    status: "现役",
    firstFlight: "1996-02-15",
    history: "90+次发射，中国发射次数最多的高轨火箭",
    height: 56.3,
    diameter: 3.35,
    mass: 459.0,
    stages: "3",
    boosters: "4 x 2.25m 液体 (N2O4/UDMH)",
    leoCapacity: 11.5,
    gtoCapacity: 5.5,
    firstStageFuel: "N2O4 / UDMH",
    firstStageEngine: "4 x YF-20C (芯级) + 4 x YF-25 (助推)",
    firstStageThrust: "5923 kN",
    secondStageFuel: "N2O4 / UDMH",
    secondStageEngine: "1 x YF-24E",
    thirdStageFuel: "液氢 / 液氧",
    thirdStageEngine: "2 x YF-75",
    description: "中国高轨道（GTO）发射任务的绝对主力。它拥有强大的液氢液氧第三级，使其能将重型通信卫星送入地球同步转移轨道。它是北斗导航卫星组网工程的最大功臣，也承担了嫦娥三号、四号等月球探测器的发射任务。",
    isReusable: false
  },
  {
    name: "CZ-4B/C",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天八院",
    status: "现役",
    firstFlight: "1999 (4B) / 2006 (4C)",
    height: 48.0,
    diameter: 3.35,
    mass: 250.0,
    stages: "3",
    boosters: "无",
    leoCapacity: 4.2,
    gtoCapacity: 1.5,
    firstStageFuel: "N2O4 / UDMH",
    firstStageEngine: "4 x YF-21C",
    thirdStageFuel: "N2O4 / UDMH",
    thirdStageEngine: "2 x YF-40",
    description: "长征四号系列是专为太阳同步轨道（SSO）设计的全常温三级火箭。CZ-4C相比4B，主要改进了三级发动机具备二次启动能力，能执行更加复杂的变轨任务。它们是“风云”气象卫星和“高分”观测卫星的主要载具。",
    isReusable: false
  },
  {
    name: "CZ-5",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院",
    status: "现役",
    firstFlight: "2016-11-03",
    history: "承担天问一号、嫦娥五号任务",
    height: 56.97,
    diameter: 5.0,
    mass: 869.0,
    stages: "2.5",
    boosters: "4 x 3.35m 液体 (液氧/煤油)",
    leoCapacity: 32.0, // 理论最大
    gtoCapacity: 14.0,
    marsCapacity: 6.0,
    plutoCapacity: 4.5, // 理论深空能力
    firstStageFuel: "液氢 / 液氧",
    firstStageEngine: "2 x YF-77 (芯级)",
    firstStageThrust: "10570 kN (含助推)",
    secondStageFuel: "液氢 / 液氧",
    secondStageEngine: "2 x YF-75D (膨胀循环)",
    description: "“胖五”，中国目前现役运力最强、体积最大的运载火箭。突破了3.35米直径限制，采用5米芯级。助推器采用液氧煤油，芯级采用液氢液氧，属于“冰箭”。它负责中国所有的重型深空探测任务，包括火星探测、月球采样返回及大型空间站舱段发射。",
    isReusable: false
  },
  {
    name: "CZ-5B",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院",
    status: "现役",
    firstFlight: "2020-05-05",
    height: 53.7,
    diameter: 5.0,
    mass: 837.0,
    stages: "1.5",
    boosters: "4 x 3.35m 液体 (液氧/煤油)",
    leoCapacity: 25.0,
    firstStageFuel: "液氢 / 液氧",
    firstStageEngine: "2 x YF-77",
    firstStageThrust: "10570 kN",
    secondStageEngine: "无 (一级直接入轨)",
    description: "长征五号的“近地轨道专用版”。它移除了第二级，拥有一级半的独特构型和巨大的整流罩（长20.5米）。它是专门为发射中国空间站“天宫”的核心舱（天和）和实验舱（问天、梦天）而设计的。",
    isReusable: false
  },
  {
    name: "CZ-6A",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天八院",
    status: "现役",
    firstFlight: "2022-03-29",
    height: 50.0,
    diameter: 3.35,
    mass: 530.0,
    stages: "2",
    boosters: "4 x 2m 固体助推器",
    leoCapacity: 4.5,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "2 x YF-100",
    firstStageThrust: "7230 kN",
    secondStageFuel: "液氧 / 煤油",
    secondStageEngine: "1 x YF-115",
    description: "中国第一款“固液混合”动力运载火箭。结合了液体发动机的高比冲和固体助推器的大推力、简单可靠。主要用于执行SSO轨道的商业组网发射任务，如“千帆星座”。支持在太原卫星发射中心进行快速发射。",
    isReusable: false
  },
  {
    name: "CZ-7",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院",
    status: "现役",
    firstFlight: "2016-06-25",
    height: 53.1,
    diameter: 3.35,
    mass: 597.0,
    stages: "2.5",
    boosters: "4 x 2.25m 液体 (液氧/煤油)",
    leoCapacity: 13.5,
    gtoCapacity: 7.0,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "2 x YF-100",
    firstStageThrust: "7200 kN",
    secondStageFuel: "液氧 / 煤油",
    secondStageEngine: "4 x YF-115",
    description: "新一代中型运载火箭的代表，全箭采用无毒无污染的液氧/煤油推进剂。它是“天舟”货运飞船的御用火箭，在文昌航天发射场执行发射任务。具备高可靠性和在台风气候下的全天候发射能力。",
    isReusable: false
  },
  {
    name: "CZ-8",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院",
    status: "现役",
    firstFlight: "2020-12-22",
    height: 50.3,
    diameter: 3.35,
    mass: 356.0,
    stages: "2",
    boosters: "2 x 2.25m 液体 (液氧/煤油)",
    leoCapacity: 8.1,
    gtoCapacity: 4.5,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "2 x YF-100",
    secondStageFuel: "液氢 / 液氧",
    secondStageEngine: "2 x YF-75",
    isReusable: true,
    recoveryMethod: "集束式垂直回收 (VTVL) - 验证阶段",
    description: "面向商业航天市场设计的新一代主力。它巧妙结合了CZ-7的煤油一级和CZ-3A的氢氧三级。设计之初就考虑了可回收性，未来的CZ-8R改型将实现芯一级与助推器的整体集束回收。",
    isReusable: true
  },
  {
    name: "CZ-9",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院",
    status: "研发中",
    firstFlight: "预计2033",
    height: 114.0,
    diameter: 10.6,
    mass: 4350.0,
    stages: "2 (或3)",
    boosters: "无 (单芯级)",
    leoCapacity: 150.0,
    marsCapacity: 44.0,
    plutoCapacity: 20.0,
    firstStageFuel: "液氧 / 甲烷",
    firstStageEngine: "30 x YF-215 (全流量分级燃烧)",
    firstStageThrust: "60000 kN",
    secondStageFuel: "液氧 / 甲烷",
    secondStageEngine: "2 x 360吨级推力",
    isReusable: true,
    recoveryMethod: "塔架抓取 / 垂直着陆",
    description: "中国航天的终极梦想——重型运载火箭。2022年方案发生重大变革，从类似SLS的构型转变为类似Starship的“光杆一级+液氧甲烷+完全复用”构型。目标是支撑载人登火、建立月球科研站及超深空探测。",
    isReusable: true
  },
  {
    name: "CZ-10",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天一院",
    status: "研发中",
    firstFlight: "预计2027",
    height: 92.0,
    diameter: 5.0,
    mass: 2189.0,
    stages: "3",
    boosters: "2 x 5.0m 通用芯级 (CBC)",
    leoCapacity: 70.0,
    marsCapacity: 27.0, // 地月转移
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "21 x YF-100K (7x3 并联)",
    firstStageThrust: "26780 kN",
    secondStageFuel: "液氢 / 液氧",
    secondStageEngine: "2 x YF-75E",
    description: "代号“921火箭”，专为2030年前实现中国人首次载人登月而研制。采用类似Falcon Heavy的CBC三核并联构型。其近地轨道版本（CZ-10A）将用于发射新一代载人飞船，且一级具备回收能力。",
    isReusable: false // 登月版不可回收，A型可回收
  },
  {
    name: "CZ-12",
    series: "长征系列",
    country: "中国",
    manufacturer: "航天八院",
    status: "现役",
    firstFlight: "2024-11-30",
    height: 62.0,
    diameter: 3.8,
    mass: 433.0,
    stages: "2",
    boosters: "无",
    leoCapacity: 12.0,
    gtoCapacity: 6.0,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "4 x YF-100K",
    secondStageFuel: "液氧 / 煤油",
    secondStageEngine: "2 x YF-115",
    description: "中国首款3.8米直径运载火箭。这一直径是铁路运输的极限。它专为海南商业航天发射场设计，采用全液氧煤油动力，填补了中国在10-12吨级LEO运力的空白。",
    isReusable: false
  },

  // ==================== 中国：商业航天 (Commercial) ====================
  {
    name: "快舟1A",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "航天科工 (ExPace)",
    status: "现役",
    height: 20.0,
    diameter: 1.4,
    mass: 30.0,
    stages: "3固体 + 1液体",
    leoCapacity: 0.3,
    firstStageFuel: "固体 (HTPB)",
    description: "“快舟”意为快速之舟。这是一款小型固体运载火箭，特色是采用车载移动发射平台，具备极强的快速响应能力，无需复杂的发射塔架，适合自然灾害应急监测卫星的快速补网。",
    isReusable: false
  },
  {
    name: "朱雀二号",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "蓝箭航天",
    status: "现役",
    firstFlight: "2022-12-14",
    height: 49.5,
    diameter: 3.35,
    mass: 219.0,
    stages: "2",
    leoCapacity: 6.0,
    firstStageFuel: "液氧 / 甲烷",
    firstStageEngine: "4 x TQ-12 (天鹊-12)",
    firstStageThrust: "2680 kN",
    secondStageFuel: "液氧 / 甲烷",
    secondStageEngine: "1 x TQ-12 (真空版) + 游机",
    description: "世界航天史上的里程碑——全球第一款成功入轨的液氧甲烷运载火箭（抢在Starship和Relativity之前）。液氧甲烷被公认为可重复使用火箭的最佳燃料，朱雀二号的成功验证了中国民营航天在新型液体动力领域的实力。",
    isReusable: false
  },
  {
    name: "朱雀三号",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "蓝箭航天",
    status: "研发中",
    firstFlight: "预计2025",
    height: 76.6,
    diameter: 4.5,
    leoCapacity: 21.3, // 不回收
    firstStageFuel: "液氧 / 甲烷",
    firstStageEngine: "9 x TQ-12B",
    isReusable: true,
    recoveryMethod: "垂直回收 (VTVL)",
    description: "中国版“猎鹰9号”。全箭主体结构采用不锈钢制造（类似Starship），这在极大降低成本的同时也带来了工艺挑战。一级设计复用次数可达20次，目标是提供极低成本的商业发射服务。",
    isReusable: true
  },
  {
    name: "力箭一号",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "中科宇航",
    status: "现役",
    firstFlight: "2022-07-27",
    height: 30.0,
    diameter: 2.65,
    mass: 135.0,
    stages: "4",
    leoCapacity: 2.0,
    firstStageFuel: "固体",
    firstStageThrust: "2000 kN",
    description: "中国科学院力学研究所孵化的商业火箭。它是目前中国最大的固体运载火箭之一，主要用于“拼车”发射微小卫星。其起飞重量和运力均创下了当时中国固体火箭的纪录。",
    isReusable: false
  },
  {
    name: "引力一号",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "东方空间",
    status: "现役",
    firstFlight: "2024-01-11",
    height: 30.0,
    diameter: 2.65,
    mass: 405.0,
    stages: "3级 + 4助推",
    boosters: "4 x 固体助推器",
    leoCapacity: 6.5,
    firstStageFuel: "固体",
    firstStageEngine: "7台发动机并联点火",
    firstStageThrust: "5880 kN",
    description: "全球起飞推力最大的固体运载火箭。外观独特，胖乎乎的造型（大直径整流罩）是为了容纳大型卫星。它采用海上发射模式，大大降低了发射区的安全风险和落区限制。",
    isReusable: false
  },
  {
    name: "谷神星一号",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "星河动力",
    status: "现役",
    firstFlight: "2020-11-07",
    height: 19.0,
    diameter: 1.4,
    mass: 33.0,
    stages: "3固体 + 1液体",
    leoCapacity: 0.4,
    description: "中国民营航天中发射频率最高、成功率最稳定的型号之一。主要服务于微纳卫星的商业组网。星河动力凭借该型号实现了公司的商业闭环。",
    isReusable: false
  },
  {
    name: "天龙二号",
    series: "中国商业航天",
    country: "中国",
    manufacturer: "天兵科技",
    status: "现役",
    firstFlight: "2023-04-02",
    height: 32.8,
    diameter: 3.35,
    leoCapacity: 2.0,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "3 x YF-102",
    description: "全球首款首飞即成功的民营液体运载火箭。打破了民营液体火箭“首飞必炸”的魔咒。它采用煤油动力，是一款中型液体火箭。",
    isReusable: false
  },

  // ==================== 美国：SpaceX / NASA / ULA ====================
  {
    name: "Falcon 9",
    series: "SpaceX",
    country: "美国",
    manufacturer: "SpaceX",
    status: "现役",
    firstFlight: "2010-06-04 (v1.0)",
    history: "300+次发射，一级复用超20次",
    height: 70.0,
    diameter: 3.7,
    mass: 549.0,
    stages: "2",
    boosters: "无",
    leoCapacity: 22.8,
    gtoCapacity: 8.3,
    marsCapacity: 4.0,
    firstStageFuel: "液氧 / 煤油 (RP-1)",
    firstStageEngine: "9 x Merlin 1D++",
    firstStageThrust: "7607 kN",
    secondStageFuel: "液氧 / 煤油 (RP-1)",
    secondStageEngine: "1 x Merlin 1D Vacuum",
    isReusable: true,
    recoveryMethod: "垂直降落 (陆地着陆场/海上驳船)",
    description: "航天史上的奇迹。它是世界上第一枚也是目前最成熟的轨道级可回收火箭。通过一级回收，它将发射成本降低了一个数量级。它是Starlink星座建设的主力，也是目前美国载人航天的唯一工具。",
    isReusable: true
  },
  {
    name: "Falcon Heavy",
    series: "SpaceX",
    country: "美国",
    manufacturer: "SpaceX",
    status: "现役",
    firstFlight: "2018-02-06",
    height: 70.0,
    diameter: 3.7,
    mass: 1420.0,
    stages: "2",
    boosters: "2 x Falcon 9 一级 (作为侧助推)",
    leoCapacity: 63.8,
    gtoCapacity: 26.7,
    marsCapacity: 16.8,
    plutoCapacity: 3.5,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "27 x Merlin 1D (含助推)",
    firstStageThrust: "22819 kN",
    secondStageFuel: "液氧 / 煤油",
    secondStageEngine: "1 x Merlin 1D Vacuum",
    isReusable: true,
    recoveryMethod: "三个一级均可垂直回收",
    description: "现役运力第二强的火箭。由三个Falcon 9的一级并联而成。首飞时同步回收两枚侧助推器的画面震撼了世界。它主要用于执行美国军方的高轨道机密任务以及NASA的重型深空探测任务（如Europa Clipper）。",
    isReusable: true
  },
  {
    name: "Starship",
    series: "SpaceX",
    country: "美国",
    manufacturer: "SpaceX",
    status: "测试中",
    firstFlight: "2023-04-20",
    height: 121.0,
    diameter: 9.0,
    mass: 5000.0,
    stages: "2 (Super Heavy + Starship)",
    boosters: "无",
    leoCapacity: 150.0,
    marsCapacity: 100.0, // 加油后
    firstStageFuel: "液氧 / 甲烷",
    firstStageEngine: "33 x Raptor 2/3",
    firstStageThrust: "74400 kN",
    secondStageFuel: "液氧 / 甲烷",
    secondStageEngine: "3 x Raptor Sea + 3 x Raptor Vac",
    isReusable: true,
    recoveryMethod: "Mechazilla 塔架“筷子”抓取",
    description: "人类历史上体积最大、推力最强的飞行器。旨在实现完全、快速的重复使用。通过“筷子”塔架空中捕获回收，省去了起落架死重。它是马斯克实现火星殖民愿景的核心工具，也是NASA Artemis计划的载人登月舱（HLS）。",
    isReusable: true
  },
  {
    name: "SLS Block 1",
    series: "NASA",
    country: "美国",
    manufacturer: "NASA / Boeing",
    status: "现役",
    firstFlight: "2022-11-16",
    height: 98.0,
    diameter: 8.4,
    mass: 2608.0,
    stages: "2",
    boosters: "2 x 五段式固体助推器 (SRB)",
    leoCapacity: 95.0,
    gtoCapacity: 27.0, // TLI
    firstStageFuel: "液氢 / 液氧",
    firstStageEngine: "4 x RS-25D (航天飞机主发)",
    firstStageThrust: "39000 kN",
    secondStageFuel: "液氢 / 液氧",
    secondStageEngine: "1 x RL10B-2 (ICPS)",
    description: "美国国家航空航天局（NASA）的巨型火箭，Artemis登月计划的基石。它大量沿用了航天飞机的遗产（发动机、助推器、燃料箱）。虽然是一次性火箭且造价极其昂贵（单发超20亿美元），但它提供了无可比拟的深空直投能力。",
    isReusable: false
  },
  {
    name: "Vulcan Centaur",
    series: "ULA",
    country: "美国",
    manufacturer: "ULA",
    status: "现役",
    firstFlight: "2024-01-08",
    height: 61.6,
    diameter: 5.4,
    mass: 546.0,
    stages: "2",
    boosters: "0/2/4/6 x GEM-63XL 固体",
    leoCapacity: 27.2,
    gtoCapacity: 14.5,
    firstStageFuel: "液氧 / 甲烷",
    firstStageEngine: "2 x BE-4 (Blue Origin)",
    firstStageThrust: "12300 kN",
    secondStageFuel: "液氢 / 液氧",
    secondStageEngine: "2 x RL10C",
    isReusable: true,
    recoveryMethod: "SMART (仅回收发动机舱) - 计划中",
    description: "联合发射联盟（ULA）的下一代主力，旨在替代昂贵的Atlas V和Delta IV。它采用了蓝色起源提供的BE-4甲烷发动机，终结了美国对俄制RD-180发动机的依赖。其Centaur V上面级性能极佳，适合高能轨道任务。",
    isReusable: true
  },
  {
    name: "New Glenn",
    series: "Blue Origin",
    country: "美国",
    manufacturer: "Blue Origin",
    status: "即将首飞",
    firstFlight: "预计2025",
    height: 98.0,
    diameter: 7.0,
    stages: "2",
    leoCapacity: 45.0,
    gtoCapacity: 13.0,
    firstStageFuel: "液氧 / 甲烷",
    firstStageEngine: "7 x BE-4",
    firstStageThrust: "17100 kN",
    secondStageFuel: "液氢 / 液氧",
    secondStageEngine: "2 x BE-3U",
    isReusable: true,
    recoveryMethod: "垂直降落 (海上平台)",
    description: "杰夫·贝佐斯的野心之作。这是一款巨大的重型运载火箭，一级设计寿命为25次复用。虽然研发进度缓慢，但其庞大的7米直径整流罩使其在发射大型卫星星座时具有独特优势。",
    isReusable: true
  },
  {
    name: "Electron",
    series: "Rocket Lab",
    country: "美国",
    manufacturer: "Rocket Lab",
    status: "现役",
    firstFlight: "2017-05-25",
    height: 18.0,
    diameter: 1.2,
    mass: 12.5,
    stages: "2",
    leoCapacity: 0.3,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "9 x Rutherford (电泵)",
    description: "小卫星发射市场的王者。它采用了独特的“电泵压”循环发动机（用电池驱动泵），全碳纤维黑色箭体极具辨识度。虽然是一次性设计，但也尝试过通过直升机空中回收一级。",
    isReusable: false
  },

  // ==================== 国际其他 (International) ====================
  {
    name: "Ariane 6",
    series: "Ariane",
    country: "欧洲",
    manufacturer: "Arianespace",
    status: "现役",
    firstFlight: "2024",
    height: 63.0,
    diameter: 5.4,
    mass: 860.0,
    stages: "2",
    boosters: "2或4 x P120C 固体",
    leoCapacity: 21.6,
    gtoCapacity: 11.5,
    firstStageFuel: "液氢 / 液氧",
    firstStageEngine: "1 x Vulcain 2.1",
    secondStageFuel: "液氢 / 液氧",
    secondStageEngine: "1 x Vinci (可再点火)",
    description: "欧洲航天局（ESA）为了应对SpaceX挑战并维持欧洲独立进入太空能力而研制的。虽然仍是一次性火箭，但通过模块化设计（A62/A64构型）降低了成本。其Vinci上面级具备多次点火能力，非常适合复杂的轨道部署。",
    isReusable: false
  },
  {
    name: "H3",
    series: "H-II",
    country: "日本",
    manufacturer: "JAXA",
    status: "现役",
    firstFlight: "2023-03-07",
    height: 63.0,
    diameter: 5.2,
    mass: 574.0,
    stages: "2",
    boosters: "0/2/4 x SRB-3",
    leoCapacity: 16.5, // 估算
    gtoCapacity: 7.9,
    firstStageFuel: "液氢 / 液氧",
    firstStageEngine: "2或3 x LE-9 (膨胀排放循环)",
    description: "日本的新一代旗舰火箭。其核心创新在于LE-9发动机，这是世界上第一款用于一级主推力的大推力“膨胀排放循环”发动机，旨在在保证高性能的同时大幅降低成本和提高可靠性。",
    isReusable: false
  },
  {
    name: "Angara A5",
    series: "Angara",
    country: "俄罗斯",
    manufacturer: "Khrunichev",
    status: "现役",
    firstFlight: "2014-12-23",
    height: 55.4,
    diameter: 8.86, // 组合体
    mass: 773.0,
    stages: "2 + 4助推",
    boosters: "4 x URM-1 (液氧/煤油)",
    leoCapacity: 24.5,
    gtoCapacity: 5.4,
    firstStageFuel: "液氧 / 煤油",
    firstStageEngine: "1 x RD-191 (芯级)",
    description: "俄罗斯后苏联时代完全自主研制的第一款重型运载火箭。采用“通用火箭模块（URM）”的模块化设计思想，通过捆绑不同数量的URM-1模块来构建轻、中、重型火箭。旨在替代使用有毒燃料的质子号火箭。",
    isReusable: false
  }
];

async function seed() {
  console.log('Starting Encyclopedia-Level Data Injection...');
  
  for (const r of rocketsData) {
    try {
      // 使用 upsert，如果已存在则更新所有字段
      await prisma.rocket.upsert({
        where: { name: r.name },
        update: r,
        create: r
      });
      console.log(`Updated Spec: ${r.name}`);
    } catch (e) {
      console.error(`Error processing ${r.name}: ${e.message}`);
    }
  }
  
  console.log('Database enriched successfully.');
}

seed()
  .catch(e => console.error(e))
  .finally(async () => {
    await prisma.$disconnect();
  });
